### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by camillo18tre** [DavidHDev/react-haiku#2]
I get " error - SyntaxError: Unexpected token 'export' " when I try to use useMousePosition();

Below my code:

```
import { useMousePosition } from 'react-haiku';

const ProjectItem = ({ project }) => {
  const { target, x, y } = useMousePosition();

  return (
    <div className="group py-5 border-b border-white grid grid-cols-3 justify-between opacity-30 hover:opacity-100 transition ease-in-out duration-700 delay-75">
      <div className="">
        {project.title}
        {/* <p className="text-xs text-gray-500">2020-2022</p> */}
      </div>
      <ul className="text-sm">
        {project.categories.map((category, catIndex) => (
          <li key={catIndex}>{category}</li>
        ))}
      </ul>
      <div className="flex justify-end group-hover:opacity-100 -translate-x-5 opacity-0 group-hover:translate-x-0 transition ease-out duration-700 delay-150">
        {'>'}
      </div>
    </div>
  );
};

export default ProjectItem;
```
<img width="2560" alt="Schermata 2022-05-30 alle 10 42 42" src="https://user-images.githubusercontent.com/38567269/170953688-c779de0c-03cf-406c-95f9-7a66c4236e7c.png">

**Comment by DavidHDev** [comment]
Hello Camillo, the reason for your error is this:

The react-haiku dependency in node_modules folder exports a function using ES6 import/export module. The code will throw error when it running in browser since browser cannot recognize the ES6 module syntax.

The reason is that, by default, Next.js configs the babel-loader to only transpile the ES6 code in the src folder, any ES6 code imported from node_modules will directly go into final bundle without transpiling.

Try to modify the webpack config in next.config.js file to let the babel loader transpile the es6 dependency. You may want to use this package [next-transpile-modules](https://github.com/martpie/next-transpile-modules#readme)

Answer found here: https://stackoverflow.com/questions/65936222/next-js-syntaxerror-unexpected-token-export

**Comment by DavidHDev** [comment]
Thank you for the steps! I will make sure to include them in the documentation soon, for other people that are using Next! Glad it works now, I'll close this issue 😇
